- name: Install Shibboleth IdP v3 
  hosts: centos-client
  remote_user: root
  
  roles:
    - webserver
    - db
    - appserver
    - idp
    - newrelic
 
  handlers:
    - name: restart apache
      service: name=httpd state=restarted

    - name: restart tomcat
      service: name=tomcat{{ tomcat_version }} state=restarted

    - name: restart MySql
      service: name=mysqld state=restarted
